services:
  rails-app:
    build: ./backend-rails
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails server -b 0.0.0.0 -p 3000 -e production"
    ports:
      - "80:3000"
    depends_on:
      - python-service
      - db
    environment:
      RAILS_ENV: production
      DATABASE_HOST: db
      DATABASE_USER: railsuser
      DATABASE_PASSWORD: railspass
      DATABASE_NAME: railsdb
      DATABASE_PORT: 5432
    volumes:
      - bundle_cache:/usr/local/bundle

  python-service:
    image: ronak834/ml_service:latest
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: railsuser
      POSTGRES_PASSWORD: railspass
      POSTGRES_DB: railsdb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  db-data:
  bundle_cache:
